language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run test:ci
true:
  branch: master
deploy:
  provider: heroku
  api_key:
    secure: OyvNX5gjoBEG0qkZeDeMo78gB2kFg+fcrZDPxKIldkcuL7bhFDR6OZTfL4dU/8pfPy4NayF6WfEwl+vPim1/pyliswJH4DhzDSsWh/XU2uG9hXmQSCjD4CbUY8RcXTWNMVKPIaaPW1VtoD5WkQzmnsHxqrI+8Kaox0lc8UpR4R9bsii5IGNXMAZSFhtXk6Lxg0kC6n9AJyQawmfDYfijM6qW/o8w2wn3DZSszQRjiMydChraJtvrLteN7TBGjScZ25z+M4pO+zZslDNT0auLPYjqFmFg3ivtIirFwki8ZIDso9/d+eq8tuJpByMombO472JHSxopk7F20C3CbFwy80JfQlzD6kD8te9+l2g0FGFr8V6l1OL/jsA2ygATyzgtXLBd7EHFuZh9Zh15SB+cOU3xInGSb70tIuI3XOyrb7eJFZAGIsikl0ZKIVQd8TawCkFE8xkptW45Uj9I1ZLmna473GsxR2HJA8+B+UgYO2ZjVHeLZ9T6pOlZOd8L9wlk8JnmaaW15JQfSjiTLuC3xk1YAYltaNxJxcy14vDjFGSb63VqCiKezDq3KQy+PkW0fs3i4Boyn9R6/F7B5dy3eOJ/kgg0aHEN9p5C/U5YtsVO/TgLLVAkVrL3JGa/e+xT+6SaXO2C2SZJIJL75guHRhdkNqkleDIymbVMMQcNEzE=
  app: mmanagement
  on:
    repo: fabioDMFerreira/money-management
