language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run test:ci
true:
  branch: master
deploy:
  provider: heroku
  api_key:
    secure: cAHKJskRNtQFrPkopx1oZAzZEJ1NV0LaG6XX5UTJPSXb/R98+X5xpOlkzVzRZnmrtBIHyp0Yxl1gwPa2i/YmSdnMBZMhk/McEK48MC/i2PrG+6wVT7oh1kUt4yz2qF3a8EzX6SVbGKXeSiRmvSRIBJKE0dgOkWwNw7BiFr7R7oC5ZGn5eatEl/BUPtewzG5BQYXiHwR1BxJhv6VQHUExawdVIL1omSRJu8yFasx0LvxsKOJVt4u3azatSm1Q/AnOQ33Vg3CSSnWfSab3ZaCSWU/08OmQIS5aA4WXs8x026o+IFzzvXBJknWSkBCPx1FokD/i+rXegYnqeyNISKpeaw7sTwGOTaiifeW2ewGYzCDVPKgIm/P7nAN2OOt4GmwLvRmv4WDDZyq+Pv2LLetawUMLnMtJxd6jh9YePgoXkXxzJAgKKWB1u5A3riB56fe2XLU1bTI/QEgFYpM3XVXR/0dce44TK6fwueolPhWDyRJGYehAXrLQrkXH726+pJtkKch+N+lda0qJ/vNQtxoW5rhxrfrjVV2bXOHpxkQL8TXfKxNLbRjWqPEh4+n/3lAz2GnNCzSxGTtPPdGYLc+Xp6y2AvNH9rPeQtFfxl7C+kpTdEPpXMXGO2UBt4CrXTnWJSnFPoKvOhH4egrGxcvTGgVciyJGXNSVHLdwBGxpwXE=
  app: mmanagement
  on:
    repo: fabioDMFerreira/money-management
