language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run test:ci
true:
  branch: master
deploy:
  provider: heroku
  api_key:
    secure: YAbPJXUD/8EWz2eCGsjoSanRjIz+0i65z68oFJDUEyI+Rpl6ggGUo8bSBlLDi0Z5oRFrD5bLRaqpec5DC+z8Cf/sqh3k+GyqDPlb4ReyO4c5LZgC5VTfbanip/1BJgDfEelZuUa+aeDlKd321vgO0ZNCQQne7NXCrVOCig5G174+rW/b22BnXOV9sG/9oho9HYlV68m2BjafEzmkc8WOYC3byp7f6hHNo1gTv/stY00DxnvsfhhJL/j7HYeffOONCzUwkkQuF4EoS3GjS8lhpUhzgzyqjjWbqT+G8AIImvcCyQXg6ZufmYe9f/TDhxcfv9zqVybRaGMbD/BxViSYMl8zxzNrVdmwebgVWKPCYxyf65RXP8m/gZKz5H1TdcFQ+HAXPClp6SXXSvvrYdr1DcFv1zsoG48FTWdcNFF4eIyCtCZSMbS9gQbjRnGUv3pCpV1YuPZpMy/SQ1xLtaMIpPIiNSYAk9aliFDGNPJ3/HlVHG8AbZhbGTQw/+cnEIWPE3qi/MmBBm6q7rdKElNCd+AsTvjOzG//2y0MM49RS31v64TTidWtnWwPMo5YsGlLM8jM24+rsu8C2JYFSqiX6kE3fFKeZHq7xOCaT4AWVJRBqjhZ8iCcvOCK/2KBQESkFvaS5UP1udZC6zzlonzhuCwW/e9zcjhwAcedfzHWp0M=
  app: mmanagement
  on:
    repo: fabioDMFerreira/money-management
