language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run test:ci
true:
  branch: master
deploy:
  provider: heroku
  api_key:
    secure: DFOsb09AO62VGhvwbzSDIBb+f9USYDTNu1DgkHV04rt64VdyjhWl9WqQJORBv7NRTEIyirIn3ToXHtiP6I92JyOROeJa3FAmvlnCUimRQJ6z6vM9dS5cXSnBnSzY6RTp3oYXGtvT1WHfeJPwgULRnOkazLZQUdP138SSTWhfs1Hwe9mVU675qW4JPWegx6lqpPbxly3GSilhpLMEgBzpxBMMuDLTo2Wm3OEGskulMS+L/7L7/k/Sbv1kUJ/DtkzPp3P+WJhifPam+1p+PxENmf6NvZE6vVHudJ8E8QH9WOHnnOsohtIKlXFS8xm3Mz9vx+wohYd9UXV/+SNEWSpdBFBmmlKuu90EAev+VQLFbsikYOlsHnG8r2LInWmg4OQCVKgOi2iAPu6pkuUb80SXxYHIB9puHAG2na+IiBBpl79VzyElVHYk+CgHMHFzxXMg8E0UTKVXJUvUrXUjqj6SsBjJefcTfYJjWLRxIUSMlT2rcNdR/5+V/IgwD7C9bTGAZxOed1xkTlebqUBXbYUELbydYYlykyHwIQ82HgCGz/KZQVhO8QvRuiKdDrNO8ExpfwZdAvRhAVxnMuke8avmXVY9s+DU6x4gie9hbffbbCtSxFRYMsFQ3mBH92riI0lSFULwCay9xyhqN0kz/JAE7HzNDAEVM3Ua8PclAtPEeTA=
  app: mmanagement
  on:
    repo: fabioDMFerreira/money-management
